---
include:
  - board: eyelash_corne_left
    shield: nice_view
  - board: eyelash_corne_right
    shield: nice_view
  - board: eyelash_corne_left
    shield: settings_reset
    artifact-name: settings_reset
